# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: system   # light, dark, system
  color: paulocv_colors

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: 'I am a Computational Epidemiology researcher specializing in data-driven models to help addressing public health challenges. With a PhD in Physics, I bring expertise in programming and advanced tools for modeling contagion dynamics through agent-based, age-structured and metapopulation simulations, as well as statistical analysis. My work is fueled by curiosity and a commitment to efficiency, so I am continuously learning new skills and tools that enhance productivity for myself and my team. My goal is to improve public wellbeing delivering precise evidence to inform decision-making on infectious diseases.'
    twitter: 'paulocv92'
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    blox: "navbar"
    fixed_to_top: true
    show_search: true
    show_theme_chooser: true
    logo:
      text: "PauloCV"

# Site footer
footer:
  copyright:
    notice: '© {year} Paulo Cesar Ventura. This work is licensed under {license}'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'

# Site features
features:
  math:
    enable: true
  privacy_pack:
    enable: false
