[build]
  command = "hugo --logLevel debug --gc --minify -b $URL"# && npx pagefind --source 'public'"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.134.0"
  HUGO_ENABLEGITINFO = "true"
  HUGO_MODULE_REPLACEMENTS="github.com/HugoBlox/hugo-blox-builder -> _vendor/github.com/HugoBlox/hugo-blox-builder"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo --logLevel debug --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"# && npx pagefind --source 'public'"

[context.branch-deploy]
  command = "hugo --logLevel debug --gc --minify -b $DEPLOY_PRIME_URL"# && npx pagefind --source 'public'"

[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"
  [plugins.inputs]
    debug = true
